name: AIPA
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.3.0
  flutter_spinkit: ^5.2.1
  url_launcher: ^6.1.14
  provider: ^6.1.2
  share_plus: ^10.1.4
  path_provider: ^2.1.5
  image: ^4.5.3
  youtube_player_flutter: ^9.1.1
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1  # Ensure this is outside `flutter_test`

flutter_icons:
  android: true
  ios: true
  image_path: "assets/Frame 1.png"  # Ensure this image exists
  adaptive_icon_background: "#ffffff"  # Optional for Android
  adaptive_icon_foreground: "assets/Frame 1.png"  # Optional

flutter:
  uses-material-design: true

  assets:
    - assets/app_icon.png 
    - assets/AIPA.png
    - assets/Frame 1.png # Ensure the icon image is included
